layout_spectrum: 0.2505964704876821
typography_spectrum: 0.19480672663843057
color:
  brandColors:
    - '#F4F2ED'
    - '#FBF9F1'
    - '#FDFDF9'
    - '#F0ECE8'
    - '#FFFFFF'
  brandStrength: 0.7487792467750093
  lightness: 0.8766481884799455
  saturation: 0.9434835509250474
  rhythmicContrast: 0.06136475605051042
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-100576145-1
  facebook: null
  twitter: null
name: 1one
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: SoCal.. SoFar..
    url: 'https://www.socalsofar.com'
    type: external
  - name: gridtalk
    url: 'http://gridtalk.info'
    type: external
  - name: '{dzign}'
    url: 'https://thegrid.ai/dzign'
    type: external
favicon: null
title: 1one
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/7cb780b0-8ddb-4f64-8f93-759e436cd727.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/7cb780b0-8ddb-4f64-8f93-759e436cd727.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'social embeds in #thegrid'
purpose: []
github: true
author:
  name: Adrian Cutler
  email: adrian@bbiab.com
